### ISSUE TITLE
test

### ISSUE THREAD

**Issue by wanghai111** [luuuyi/RefineDet.PyTorch#14]
Traceback (most recent call last):
  File "/home/hai/A_pytorch/RefineDet.PyTorch-master/eval_refinedet.py", line 445, in <module>
    thresh=args.confidence_threshold)
  File "/home/hai/A_pytorch/RefineDet.PyTorch-master/eval_refinedet.py", line 392, in test_net
    detections = net(x).data
  File "/home/hai/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hai/A_pytorch/RefineDet.PyTorch-master/models/refinedet.py", line 148, in forward
    self.priors.type(type(x.data))                  # default boxes
  File "/home/hai/A_pytorch/RefineDet.PyTorch-master/layers/functions/detection_refinedet.py", line 48, in forward
    self.num_classes).transpose(2, 1)
RuntimeError: invalid argument 2: size '[1 x 8732 x 16]' is invalid for input with 102000 elements at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/TH/THStorage.cpp:84

**Comment by luuuyi** [comment]
@wanghai111 it seems that your input data size is not matched, you can check it
