### ISSUE TITLE
when i sh train_refinedet320.sh,something is wrong

### ISSUE THREAD

**Issue by rw1995** [luuuyi/RefineDet.PyTorch#15]
cuda  9.0, cudnn 7.3, pytorch0.4.0+python3.6

i follow your suggestion,but when i sh train_refinedet320.sh,of course i decrease the batch_size=4
but something is wrong
`(pytorch0.4.0) rw@rw:~/RefineDet.PyTorch$ sh ./train_refinedet320.sh
RefineDet(
  (vgg): ModuleList(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=True)
    (17): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (18): ReLU(inplace)
    (19): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (20): ReLU(inplace)
    (21): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (22): ReLU(inplace)
    (23): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (24): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (25): ReLU(inplace)
    (26): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (27): ReLU(inplace)
    (28): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (29): ReLU(inplace)
    (30): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (31): Conv2d(512, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(3, 3), dilation=(3, 3))
    (32): ReLU(inplace)
    (33): Conv2d(1024, 1024, kernel_size=(1, 1), stride=(1, 1))
    (34): ReLU(inplace)
  )
  (conv4_3_L2Norm): L2Norm()
  (conv5_3_L2Norm): L2Norm()
  (extras): ModuleList(
    (0): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
    (1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  )
  (arm_loc): ModuleList(
    (0): Conv2d(512, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): Conv2d(512, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): Conv2d(1024, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): Conv2d(512, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (arm_conf): ModuleList(
    (0): Conv2d(512, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): Conv2d(512, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): Conv2d(1024, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): Conv2d(512, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (odm_loc): ModuleList(
    (0): Conv2d(256, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): Conv2d(256, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): Conv2d(256, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): Conv2d(256, 12, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (odm_conf): ModuleList(
    (0): Conv2d(256, 63, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): Conv2d(256, 63, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): Conv2d(256, 63, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): Conv2d(256, 63, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (tcb0): ModuleList(
    (0): Conv2d(512, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace)
    (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): Conv2d(512, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): ReLU(inplace)
    (5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): Conv2d(1024, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace)
    (8): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): Conv2d(512, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (10): ReLU(inplace)
    (11): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (tcb1): ModuleList(
    (0): ConvTranspose2d(256, 256, kernel_size=(2, 2), stride=(2, 2))
    (1): ConvTranspose2d(256, 256, kernel_size=(2, 2), stride=(2, 2))
    (2): ConvTranspose2d(256, 256, kernel_size=(2, 2), stride=(2, 2))
  )
  (tcb2): ModuleList(
    (0): ReLU(inplace)
    (1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): ReLU(inplace)
    (3): ReLU(inplace)
    (4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): ReLU(inplace)
    (6): ReLU(inplace)
    (7): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace)
    (9): ReLU(inplace)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace)
  )
)
Loading base network...
Initializing weights...
Loading the dataset...
Training RefineDet on: VOC0712
Using the specified args:
Namespace(basenet='./weights/vgg16_reducedfc.pth', batch_size=4, cuda=True, dataset='VOC', dataset_root='/home/rw/data/datasets/VOCdevkit/', gamma=0.1, input_size='320', lr=0.001, momentum=0.9, num_workers=8, resume=None, save_folder='weights/RefineDet320/', start_iter=0, visdom=False, weight_decay=0.0005)
Traceback (most recent call last):
  File "train_refinedet.py", line 288, in <module>
    train()
  File "train_refinedet.py", line 166, in train
    batch_iterator = iter(data_loader)
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 247, in __init__
    self._put_indices()
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 295, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 138, in __iter__
    for idx in self.sampler:
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 51, in __iter__
    return iter(torch.randperm(len(self.data_source)).tolist())
RuntimeError: randperm is only implemented for CPU
`

please tell me what should i do?

**Comment by rw1995** [comment]
Loading base network...
Initializing weights...
Loading the dataset...
Training RefineDet on: VOC0712
Using the specified args:
Namespace(basenet='./weights/vgg16_reducedfc.pth', batch_size=4, cuda=True, dataset='VOC', dataset_root='/home/rw/data/datasets/VOCdevkit/', gamma=0.1, input_size='320', lr=0.001, momentum=0.9, num_workers=8, resume=None, save_folder='weights/RefineDet320/', start_iter=0, visdom=False, weight_decay=0.0005)
Traceback (most recent call last):
  File "train_refinedet.py", line 288, in <module>
    train()
  File "train_refinedet.py", line 166, in train
    batch_iterator = iter(data_loader)
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 247, in __init__
    self._put_indices()
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 295, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 138, in __iter__
    for idx in self.sampler:
  File "/home/rw/anaconda3/envs/pytorch0.4.0/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 51, in __iter__
    return iter(torch.randperm(len(self.data_source)).tolist())
**RuntimeError: randperm is only implemented for CPU**

**Comment by rw1995** [comment]
wow,i solve it  
i run the project on the environment -- cuda 9 + cudnn7 +pytorch0.4.1 + python3.5  
thank you for the greatest code
