### ISSUE TITLE
when i test the code i have meet problems

### ISSUE THREAD

**Issue by YYZ-rose** [luuuyi/RefineDet.PyTorch#25]

**Comment by YYZ-rose** [comment]
@node3:~/RefineDet.PyTorch$ python eval_refinedet.py
Traceback (most recent call last):
  File "eval_refinedet.py", line 427, in <module>
    net = build_refinedet('test', int(args.input_size), num_classes)                                                                                  # initialize SSD
  File "/home/yangyuze/RefineDet.PyTorch/models/refinedet.py", line 292, in buil                                                                      d_refinedet
    return RefineDet(phase, size, base_, extras_, ARM_, ODM_, TCB_, num_classes)
  File "/home/yangyuze/RefineDet.PyTorch/models/refinedet.py", line 33, in __ini                                                                      t__
    self.priorbox = PriorBox(self.cfg[str(size)])
KeyError: '512'

**Comment by YYZ-rose** [comment]
@luuuyi

**Comment by luuuyi** [comment]
@YYZ-rose you should check and debug your cfg, as you see, 512 is not a key in a dict.
