### ISSUE TITLE
train on my datasets

### ISSUE THREAD

**Issue by yanelezk** [luuuyi/RefineDet.PyTorch#28]

**Comment by yanelezk** [comment]
KeyError: 'Traceback (most recent call last):\n  File "/home/wncc/anaconda3/envs/Track/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/wncc/anaconda3/envs/Track/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/wncc/RefineDet.PyTorch/data/voc0712.py", line 110, in __getitem__\n    im, gt, h, w = self.pull_item(index)\n  File "/home/wncc/RefineDet.PyTorch/data/voc0712.py", line 125, in pull_item\n    target = self.target_transform(target, width, height)\n  File "/home/wncc/RefineDet.PyTorch/data/voc0712.py", line 67, in __call__\n    label_idx = self.class_to_ind[name]\nKeyError: \'trepang\'\n'
