### ISSUE TITLE
train_refinedet.py RunError

### ISSUE THREAD

**Issue by RNG-cz** [luuuyi/RefineDet.PyTorch#39]
Traceback (most recent call last):

  File "<ipython-input-2-5c85d620cdf3>", line 1, in <module>
    runfile('C:/Users/leevov/Desktop/RefineDet.PyTorch-master/train_refinedet.py', wdir='C:/Users/leevov/Desktop/RefineDet.PyTorch-master')

  File "C:\Users\leevov\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\leevov\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/leevov/Desktop/RefineDet.PyTorch-master/train_refinedet.py", line 288, in <module>
    train()

  File "C:/Users/leevov/Desktop/RefineDet.PyTorch-master/train_refinedet.py", line 166, in train
    batch_iterator = iter(data_loader)

  File "C:\Users\leevov\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)

  File "C:\Users\leevov\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()

  File "C:\Users\leevov\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)

  File "C:\Users\leevov\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\leevov\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\Users\leevov\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\leevov\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by immarioo** [comment]
i think there may be some errors in your datasets, may be you should check it first.
