### ISSUE TITLE
eval_refinedet.py RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method.

### ISSUE THREAD

**Issue by sdwangyifan001** [luuuyi/RefineDet.PyTorch#47]
E:\anaconda\envs\env_ref\python.exe E:/code/RefineDet.PyTorch-master/eval_refinedet.py
Finished loading model!
Traceback (most recent call last):
  File "E:/code/RefineDet.PyTorch-master/eval_refinedet.py", line 441, in <module>
    tet_net(args.save_folder, net, args.cuda, dataset,
  File "E:/code/RefineDet.PyTorch-master/eval_refinedet.py", line 389, in tet_net
    detections = net(x).data
  File "E:\anaconda\envs\env_ref\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\code\RefineDet.PyTorch-master\models\refinedet.py", line 141, in forward
    output = self.detect(
  File "E:\anaconda\envs\env_ref\lib\site-packages\torch\autograd\function.py", line 148, in __call__
    raise RuntimeError(
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

Process finished with exit code 1
I wouldn't like to use pytorch=1.2.0, and there is also '@staticmethod' in my code.
what can I do to solve the problem?

**Comment by sdwangyifan001** [comment]
thanks. i've got it.

**Comment by hali6779** [comment]
Hi, I'm using pytorch 1.5.0, may I know how do you solved it, thanks in advance. @sdwangyifan001
